### ISSUE TITLE
Realtime Benchmark

### ISSUE THREAD

**Issue by kiwicopple** [supabase/benchmarks-archive#12]
# Chore

As part of our move from Alpha to Beta, we will want to be clear about the limitations and performance of each of the components in Supabase. We need to do 3 things:

- [ ] Design a benchmark  (if it isn't already designed)
- [ ] Perform the benchmark
- [ ] Create a blog post or documentation detailing the results

**Comment by soedirgo** [comment]
## Preliminary results

### Setup
- Postgres: AWS supabase-postgres-0.13.0 image (t2.micro)
- Realtime: AWS supabase-realtime-0.7.5 image (t2.micro)
- Client: My laptop

One small annoyance: need to uncap the no. of open file descriptors for the Realtime server and possibly the client. (More info [here](https://www.rabbitmq.com/install-rpm.html#kernel-resource-limits)). There's also a section for this in Phoenix's 2m WebSockets [article](https://phoenixframework.org/blog/the-road-to-2-million-websocket-connections), might want to follow it as well.

- /etc/sysctl.conf
```
...
fs.nr_open=2147483584
fs.file-max=2147483584
```
- /etc/systemd/system/realtime.service
```
[Service]
...
LimitNOFILE=214783584
```
- Restart
- Run `ulimit -n 214783584`

### Postgres schema
```sql
ALTER SYSTEM SET wal_level = logical;
ALTER SYSTEM SET max_replication_slots = 5;
CREATE PUBLICATION supabase_realtime FOR ALL TABLES;

CREATE TABLE foo (id SERIAL);
ALTER TABLE foo REPLICA IDENTITY FULL;
```

### Load
- 1 `INSERT` per second
- 1000 subscriptions (code is slightly modified from supabase/realtime/examples/node-js)

### Result
CPU utilization at 7%. If we ignore Amdahl's Law, a ~10x machine would get us to 100k :)

**Comment by inian** [comment]
Great work on setting this up Bobbie. Have you pushed the benchmarking code somewhere? 

Can you test on the following instances as well?
- t3a.micro
- t4g.micro (you will need to use supabase-postgres-arm-0.13.0 image for this in the tokyo region)

For next steps, it would be interesting to know what load would push the CPU to 100% (or is memory the bottleneck?) on these instances..

**Comment by soedirgo** [comment]
👌

The only relevant code I guess is the node-js realtime example code, I'll try working on a reproducible bench suite with the modified code and AWS CLI/SDK (or if you have something like this, I'll use that).

Other next steps:
- Use a dedicated instance for the client (maybe use Tsung? Easy to automate increasing WS connections)
- Use a more realistic Postgres schema
- Bench throughput (max. events per second)

**Comment by inian** [comment]
Couple of other points which may help
- Make sure that the client instance is in the same subnet as the instance you are benchmarking. That made a huge difference in another benchmark I did
- For a more realistic schema, consider using [Chinook](https://github.com/lerocha/chinook-database/wiki/Chinook-Schema). Our postgrest benchmark [uses it](https://github.com/supabase/benchmarks/blob/master/postgrest/sql/chinook.sql).
