### ISSUE TITLE
Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/benchmarks-archive#25]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 30 46 PM" src="https://user-images.githubusercontent.com/70828596/146444837-cf907cd6-05e6-4212-9165-128a440ea9d5.png">

**Comment by steve-chavez** [comment]
Unfortunately I don't have the privileges to do that.
